name: apply-heml-template
description: Apply the helm template
author: Arley Fernandez
inputs:
  host_list:
    required: true
    description: 'input description here'
  consul_host:
    required: true
    description: 'input description here'
  consul_token:
    required: true
    description: 'input description here'
  config_path:
    required: true
    description: 'input description here'
  ssh_key:
    required: true
    description: 'input description here'
  vm_user:
    required: true
    description: 'input description here'
  ansible_extra_vars:
    required: true
    description: 'comma separate ansible extra vars' 
runs:
  using: 'node16'
  main: 'dist/index.js'
